export const exportParityConfig = {
  ignoredKeys: ['default', '__esModule'],
  extraWebExports: [] as string[],
  omittedWebExports: [
    'calculateGridContentDimensions',
    'calculateGridPosition',
    'calculateIndexFromRowColumn',
    'findItemIdAtIndex',
    'getGridCellFromCoordinates',
    'GridOrientation',
    'GridScrollDirection',
    'GridStrategy',
    'listToGridObject',
    'reorderGridInsert',
    'reorderGridSwap',
    'setGridAutoScroll',
    'setGridPosition',
    'SortableGrid',
    'SortableGridItem',
    'useGridSortable',
    'useGridSortableList',
  ],
} as const;
